# Generated by Django 4.1.5 on 2023-07-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configurations",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=100, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=100, verbose_name="Key")),
                ("value", models.CharField(max_length=100, verbose_name="Value")),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=100, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "status",
                    models.CharField(
                        choices=[["Created", "Created"], ["Sent", "Sent"]],
                        default="Pending",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Payload")),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AddField(
            model_name="consignment",
            name="isbillGenerated",
            field=models.BooleanField(default=False, verbose_name="Bill Generated"),
        ),
        migrations.AddField(
            model_name="location",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[("ODA", "ODA"), ("Normal", "Normal")],
                default="Normal",
                max_length=100,
                verbose_name="Location Type",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="rate",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="fixedCharge",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Fixed Charge"
            ),
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="miscCharge",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Misc Charge"
            ),
        ),
        migrations.AddField(
            model_name="vendordetails",
            name="odaCharge",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="ODA Charge"
            ),
        ),
        migrations.AlterField(
            model_name="vendorlocation",
            name="createdDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="ReverseConsignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=100, null=True)),
                ("dcNo", models.CharField(max_length=100, verbose_name="DC No")),
                ("dcDate", models.DateField(verbose_name="DC Date")),
                ("dcConfirm", models.DateField(verbose_name="DC Confirm")),
                ("dcAgeing", models.IntegerField(verbose_name="DC Ageing")),
                ("reqToVendor", models.DateField(verbose_name="Req. To Vendor")),
                (
                    "pickupReqAgeing",
                    models.IntegerField(verbose_name="Pickup Req. Ageing"),
                ),
                ("dcQty", models.IntegerField(verbose_name="DC Qty")),
                ("remark", models.TextField(verbose_name="Remark")),
                (
                    "ageingStatus",
                    models.CharField(
                        choices=[
                            ["Critical", "Critical"],
                            ["High", "High"],
                            ["Medium", "Medium"],
                            ["Low", "Low"],
                        ],
                        default="low",
                        max_length=100,
                        verbose_name="Ageing Status",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ["Created", "Created"],
                            ["Picked", "Picked"],
                            ["In-transit", "In-transit"],
                            ["OutForDelivery", "OutForDelivery"],
                            ["Delivered", "Delivered"],
                        ],
                        default="Created",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                (
                    "distributorName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="distributorName",
                        to="crm.vendordetails",
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reverse Consignment",
                "verbose_name_plural": "Reverse Consignments",
            },
        ),
    ]
