# Generated by Django 4.1.5 on 2023-07-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_configurations_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consignment",
            name="cp_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consignment",
            name="distributor_ids",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="consignment",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="consignment_location",
                to="crm.location",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="consignment",
            name="location_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
