# Generated by Django 4.1.5 on 2023-07-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_consignment_cp_id_consignment_distributor_ids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consignment",
            name="status",
            field=models.CharField(
                choices=[
                    ["Created", "Created"],
                    ["In-transit", "In-transit"],
                    ["Reached", "Reached"],
                    ["Out For Delivery", "Out For Delivery"],
                    ["Delivered", "Delivered"],
                    ["Attempted", "Attempted"],
                    ["Returned", "Returned"],
                    ["undelivered", "undelivered"],
                ],
                default="Created",
                max_length=100,
                verbose_name="Consignment Status",
            ),
        ),
        migrations.AlterField(
            model_name="vendorlocation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendorLocation",
                to="crm.location",
            ),
        ),
    ]
