# Generated by Django 4.1.5 on 2023-07-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_consignment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reverseconsignment",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="reverseconsignment",
            name="distributorName",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="distributorName",
                to="crm.consigneeconsigner",
                verbose_name="Name",
            ),
        ),
    ]
