# Generated by Django 4.1.5 on 2023-07-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_reverseconsignment_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reverseconsignment",
            name="lrNo",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="lr No."
            ),
        ),
        migrations.AlterField(
            model_name="consignment",
            name="reverseDocketNo",
            field=models.CharField(
                blank=True,
                default=0,
                max_length=100,
                null=True,
                verbose_name="Reverse Docket Number",
            ),
        ),
        migrations.AlterField(
            model_name="reverseconsignment",
            name="ageingStatus",
            field=models.CharField(
                choices=[
                    ["Critical", "Critical"],
                    ["High", "High"],
                    ["Medium", "Medium"],
                    ["Low", "Low"],
                ],
                default="Low",
                max_length=100,
                verbose_name="Ageing Status",
            ),
        ),
        migrations.AlterField(
            model_name="reverseconsignment",
            name="status",
            field=models.CharField(
                choices=[["Created", "Created"], ["Picked", "Picked"]],
                default="Created",
                max_length=100,
                verbose_name="Status",
            ),
        ),
    ]
