# Generated by Django 5.0.6 on 2024-05-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_reverseconsignment_lrno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configurations',
        ),
        migrations.RemoveField(
            model_name='consignmentaudit',
            name='consignee_id',
        ),
        migrations.RemoveField(
            model_name='consignmentaudit',
            name='consigner_id',
        ),
        migrations.RemoveField(
            model_name='consignmentaudit',
            name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='consignmentaudit',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='consignmentaudit',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='loan_linked',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='coloader_id',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='manifestId',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.RemoveField(
            model_name='reverseconsignment',
            name='distributorName',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='createdDate',
            new_name='lrDate',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='cp_id',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='distributor_ids',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='isbillGenerated',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='location_name',
        ),
        migrations.DeleteModel(
            name='ConsignmentAudit',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Manifest',
        ),
        migrations.DeleteModel(
            name='ReverseConsignment',
        ),
    ]
