# Generated by Django 4.1 on 2024-07-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_delete_configurations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHolidays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
            },
        ),
        migrations.AddField(
            model_name='consigneeconsigner',
            name='tat',
            field=models.IntegerField(blank=True, default=None, max_length=3, null=True, verbose_name='Tat'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='expectedDeliveryDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='mode',
            field=models.CharField(choices=[['forward', 'forward'], ['reverse', 'reverse']], default='forward', max_length=100, verbose_name='Consignment Mode'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='status',
            field=models.CharField(choices=[['created', 'created'], ['in-transit', 'in-transit'], ['reached', 'reached'], ['out-for-delivery', 'out-for-delivery'], ['delivered', 'delivered'], ['attempted', 'attempted'], ['returned', 'returned'], ['undelivered', 'undelivered']], default='created', max_length=100, verbose_name='Consignment Status'),
        ),
    ]
