# Generated by Django 4.1 on 2024-07-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_publicholidays_consigneeconsigner_tat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='tatstatus',
            field=models.CharField(blank=True, choices=[['passed', 'passed'], ['failed', 'failed']], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consignment',
            name='variance',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='consigneeconsigner',
            name='tat',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Tat'),
        ),
    ]
