# Generated by Django 4.1 on 2024-07-05 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_consignment_variance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='tatstatus',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='variance',
        ),
        migrations.CreateModel(
            name='Billings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tatstatus', models.CharField(blank=True, choices=[['passed', 'passed'], ['failed', 'failed']], default=None, max_length=10, null=True)),
                ('variance', models.IntegerField(blank=True, default=None, null=True)),
                ('chargeableWeight', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additionalCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odaCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_chargeableWeight', models.IntegerField()),
                ('cp_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_additionalCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_odaCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coloaderCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicleCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miscCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miscRemark', models.TextField()),
                ('labourCharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('officeExpense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('lr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consignment_billings', to='crm.consignment')),
            ],
        ),
    ]
