# Generated by Django 4.1 on 2024-07-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_remove_consignment_tatstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billings',
            name='consigneeId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='billings',
            name='consigneeName',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='billings',
            name='consignerId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='billings',
            name='consignerName',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='billings',
            name='locationId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='billings',
            name='locationName',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='consignment',
            name='tatstatus',
            field=models.CharField(blank=True, choices=[['passed', 'passed'], ['failed', 'failed']], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consignment',
            name='variance',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
