# Generated by Django 4.1 on 2024-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_billings_consigneeid_billings_consigneename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consignment',
            name='delayedReason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='consignment',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consignment',
            name='notifiedDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
