# Generated by Django 4.1 on 2024-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_billings_coloadercharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='additionalCharges',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consignment',
            name='additionalChargesReason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
