# Generated by Django 4.1 on 2024-07-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_consignment_additionalcharges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consigneeconsigner',
            name='odaCharge',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ODA Charges'),
        ),
        migrations.AddField(
            model_name='consigneeconsigner',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='billings',
            name='additionalCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billings',
            name='chargeableWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billings',
            name='cp_additionalCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='cp_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billings',
            name='cp_chargeableWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billings',
            name='cp_odaCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='cp_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billings',
            name='cp_totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billings',
            name='labourCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='miscCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='odaCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='officeExpense',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billings',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billings',
            name='vehicleCharge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='additionalCharges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
