# Generated by Django 4.1 on 2024-07-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_consigneeconsigner_odacharge_consigneeconsigner_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consigneeconsigner',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Phone'),
        ),
    ]
