# Generated by Django 4.1 on 2024-07-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_consigneeconsigner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consigneeconsigner',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
