# Generated by Django 4.1 on 2024-07-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_consigneeconsigner_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billings',
            name='lr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_billings', to='crm.consignment'),
        ),
    ]
