# Generated by Django 4.1 on 2024-08-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_billings_lr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.RemoveField(
            model_name='consigneeconsigner',
            name='locationMappingId',
        ),
        migrations.RemoveField(
            model_name='location',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='location',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='modifiedBy',
        ),
        migrations.RemoveField(
            model_name='location',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
        migrations.AddField(
            model_name='consigneeconsigner',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributors', to='crm.vendordetails', verbose_name='Channel Partner'),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_partners', to='crm.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='billings',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consigneeconsigner',
            name='createdDate',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='consigneeconsigner',
            name='deletedOn',
            field=models.DateField(auto_now=True, null=True, verbose_name='Deleted On'),
        ),
        migrations.AlterField(
            model_name='consigneeconsigner',
            name='modifiedDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='deletedOn',
            field=models.DateField(auto_now=True, verbose_name='Deleted On'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='modifiedDate',
            field=models.DateField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='modifiedDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicholidays',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicholidays',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='deletedOn',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='modifiedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='createdDate',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='deletedOn',
            field=models.DateField(null=True, verbose_name='Deleted On'),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='modifiedDate',
            field=models.DateField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='phone',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.DeleteModel(
            name='VendorLocation',
        ),
    ]
