# Generated by Django 4.1 on 2024-08-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_billings_lr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='phone',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone'),
        ),
    ]
