# Generated by Django 4.1 on 2024-08-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_delete_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billings',
            old_name='lr',
            new_name='consignment',
        ),
    ]
