# Generated by Django 4.1 on 2024-08-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_vendordetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
