# Generated by Django 4.1 on 2024-08-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_vendordetails_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='deletedOn',
        ),
    ]
