# Generated by Django 4.1 on 2024-08-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_vendordetails_deletedon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
