# Generated by Django 4.1 on 2024-08-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_delete_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorLocation',
        ),
    ]
