# Generated by Django 4.1 on 2024-08-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_delete_vendorlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consigneeconsigner',
            name='locationMappingId',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
