# Generated by Django 4.1 on 2024-08-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_consigneeconsigner_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consigneeconsigner',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='consigneeconsigner',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributors', to='crm.vendordetails', verbose_name='Vendor'),
        ),
    ]
