# Generated by Django 4.1 on 2024-08-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_remove_consigneeconsigner_vendor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consigneeconsigner',
            name='vendor',
        ),
        migrations.AddField(
            model_name='consigneeconsigner',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_vendor_id', to='crm.vendordetails', verbose_name='Channel Partner'),
        ),
    ]
