# Generated by Django 4.1 on 2024-08-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_location_alter_consigneeconsigner_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_partners', to='crm.location', verbose_name='Location'),
        ),
    ]
